Sprint 22
purpleratchet/PlaylistMaker pull request #16
Opened 2024-03-14 11:44 UTC by purpleratchet

Initial Pull Request for Sprint 22

2024-03-14 23:40 UTC, DmitrijEgorow requested changes

2024-03-14 23:40 UTC, DmitrijEgorow commented on app/build.gradle
> +    implementation 'com.github.tbruyelle:rxpermissions:v0.12'
Точно нужно подключать?

2024-03-14 23:40 UTC, DmitrijEgorow commented on app/build.gradle
> +    implementation "androidx.activity:activity:1.8.2"
Стоит унифицировать: где-то скобочки появились

2024-03-14 23:40 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/PlayerFragment.kt
> +                        "Трек уже добавлен в плейлист" + " ${playlistTrackState.nameOfPlaylist}"
Лучше string-res, иначе возникнут сложности при локализации

2024-03-14 23:40 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/viewmodel/PlayerViewModel.kt
> +    private fun convertStringToList(string: String): ArrayList<Int> {
Можно вынести в отдельный utils-класс

2024-03-14 23:40 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_new_playlist.xml
> +        android:id="@+id/new_playlist_button"
Стоит унифицировать стиль идентификаторов, немного выше:
`android:id="@+id/filledTextFieldDescription"`

2024-03-14 23:42 UTC, DmitrijEgorow commented
Приложение аварийно завершается при попытке перейти назад


https://github.com/purpleratchet/PlaylistMaker/assets/36837067/37272aea-46ec-4702-a38c-ef6e95d47703

```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 30456  
java.lang.IllegalStateException: Fragment NewPlaylistFragment{39840d2} (22f26580-56ee-40d9-b5c9-19fc37c98082) not associated with a fragment manager.  
at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)  
at androidx.navigation.fragment.NavHostFragment$Companion.findNavController(NavHostFragment.kt:353)  
at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)  
at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.checkForDialogOutput(NewPlaylistFragment.kt:149)  
at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.access$checkForDialogOutput(NewPlaylistFragment.kt:34)  
at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment$onViewCreated$1.handleOnBackPressed(NewPlaylistFragment.kt:67)  
at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)  
at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)  
at android.app.Activity.onKeyUp(Activity.java:3905)  
at android.view.KeyEvent.dispatch(KeyEvent.java:3688)  
at android.app.Activity.dispatchKeyEvent(Activity.java:4230)  
at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)  
at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)  
at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)  
at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)  
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)  
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)  
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)  
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)  
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)  
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)  
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)  
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)  
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)  
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)  
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)  
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)  
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)  
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)  
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)  
at android.os.MessageQueue.nativePollOnce(Native Method)  
at android.os.MessageQueue.next(MessageQueue.java:335)
```

2024-03-14 23:43 UTC, DmitrijEgorow commented
Кнопка "Очистить историю" должна показываться только, когда есть список недавних треков


https://github.com/purpleratchet/PlaylistMaker/assets/36837067/a9261ac9-c3ec-40ec-9a01-5fe6c9c5a91a

2024-03-14 23:44 UTC, DmitrijEgorow commented
Курсор должен быть синего цвета согласно дизайну
![Screenshot_20240315_010003](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/83a928ae-6a8e-4ab3-b9ec-2df55b77464c)

2024-03-14 23:45 UTC, DmitrijEgorow commented
На этом экране не должно быть нижнего меню навигации
![Screenshot_20240315_010035](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/4b82dbee-9a08-402a-9f03-5763ae2a334b)

2024-03-14 23:47 UTC, DmitrijEgorow commented
- [ ] "Медиатека" имеет сильно большой отступ слева
- [ ] Изображение плейсхолдера нужно растянуть внутри карточки и убрать цвет заливки (как в дизайн-макете)
- [ ] Сильно большой отступ между "Новый плейлист" и самим списком
![Screenshot_20240315_011050](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/d2109ba7-7953-4ee6-be6c-8a8ee20c4f1f)
![Screenshot_20240315_011220](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/5d37dec9-4e5a-47e5-aad3-94e75fc0bec9)

2024-03-14 23:48 UTC, DmitrijEgorow commented
Низкий контраст цвета текста, нужно поменять

![Screenshot_20240315_013149](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/6e125127-1179-49fd-8505-cbad16af4b02)

2024-03-15 13:29 UTC, purpleratchet commented
> Приложение аварийно завершается при попытке перейти назад
> 
>  Screen_recording_20240315_021919.mp4 
> ```
> FATAL EXCEPTION: main  
> Process: com.example.playlistmaker, PID: 30456  
> java.lang.IllegalStateException: Fragment NewPlaylistFragment{39840d2} (22f26580-56ee-40d9-b5c9-19fc37c98082) not associated with a fragment manager.  
> at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)  
> at androidx.navigation.fragment.NavHostFragment$Companion.findNavController(NavHostFragment.kt:353)  
> at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)  
> at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.checkForDialogOutput(NewPlaylistFragment.kt:149)  
> at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.access$checkForDialogOutput(NewPlaylistFragment.kt:34)  
> at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment$onViewCreated$1.handleOnBackPressed(NewPlaylistFragment.kt:67)  
> at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)  
> at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)  
> at android.app.Activity.onKeyUp(Activity.java:3905)  
> at android.view.KeyEvent.dispatch(KeyEvent.java:3688)  
> at android.app.Activity.dispatchKeyEvent(Activity.java:4230)  
> at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)  
> at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)  
> at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)  
> at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)  
> at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)  
> at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)  
> at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)  
> at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)  
> at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)  
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)  
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)  
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
> at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)  
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)  
> at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)  
> at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)  
> at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)  
> at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)  
> at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)  
> at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)  
> at android.os.MessageQueue.nativePollOnce(Native Method)  
> at android.os.MessageQueue.next(MessageQueue.java:335)
> ```



> 

я смог воспроизвести этот баг лишь 1 раз, дальше не воспроизводится...

2024-03-19 13:00 UTC, DmitrijEgorow commented
> > Приложение аварийно завершается при попытке перейти назад
> > Screen_recording_20240315_021919.mp4
> > ```
> > FATAL EXCEPTION: main  
> > Process: com.example.playlistmaker, PID: 30456  
> > java.lang.IllegalStateException: Fragment NewPlaylistFragment{39840d2} (22f26580-56ee-40d9-b5c9-19fc37c98082) not associated with a fragment manager.  
> > at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)  
> > at androidx.navigation.fragment.NavHostFragment$Companion.findNavController(NavHostFragment.kt:353)  
> > at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)  
> > at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.checkForDialogOutput(NewPlaylistFragment.kt:149)  
> > at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment.access$checkForDialogOutput(NewPlaylistFragment.kt:34)  
> > at com.example.playlistmaker.library.ui.fragment.NewPlaylistFragment$onViewCreated$1.handleOnBackPressed(NewPlaylistFragment.kt:67)  
> > at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)  
> > at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)  
> > at android.app.Activity.onKeyUp(Activity.java:3905)  
> > at android.view.KeyEvent.dispatch(KeyEvent.java:3688)  
> > at android.app.Activity.dispatchKeyEvent(Activity.java:4230)  
> > at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)  
> > at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)  
> > at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)  
> > at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)  
> > at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)  
> > at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)  
> > at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)  
> > at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)  
> > at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)  
> > at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)  
> > at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> > at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> > at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)  
> > at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
> > at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)  
> > at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
> > at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> > at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> > at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)  
> > at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)  
> > at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)  
> > at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)  
> > at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)  
> > at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)  
> > at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)  
> > at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)  
> > at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)  
> > at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)  
> > at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)  
> > at android.os.MessageQueue.nativePollOnce(Native Method)  
> > at android.os.MessageQueue.next(MessageQueue.java:335)
> > ```
> 
> > 
> 
> я смог воспроизвести этот баг лишь 1 раз, дальше не воспроизводится...

Можно попробовать сначала снести приложение и установить начисто (или очистить кеш)

2024-03-19 13:00 UTC, DmitrijEgorow commented
> Низкий контраст цвета текста, нужно поменять
> 
> ![Screenshot_20240315_013149](https://private-user-images.githubusercontent.com/36837067/313024503-6e125127-1179-49fd-8505-cbad16af4b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTM0MjYsIm5iZiI6MTcxMDg1MzEyNiwicGF0aCI6Ii8zNjgzNzA2Ny8zMTMwMjQ1MDMtNmUxMjUxMjctMTE3OS00OWZkLTg1MDUtY2JhZDE2YWY0YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEyNTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTI5ZTFkOWJhMTYxMzNmNGRjYjFlMmIxZjQ2Mzc4YTcwNDJmMmEzMTU3MWU2OGU4YzRhMWRhOWQ1YWRmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Om9_9mSgiMyJPL8VWmZ5YgvIVXS5WqtLJcf8PAn9Pug)

Актуально

2024-03-19 13:02 UTC, DmitrijEgorow commented
Стоит динамически растягивать/сжимать изображение плейсхолдера, это обеспечит адаптивность разметки

![Screenshot_20240319_152549](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/cffb43d8-4a56-43a8-8e72-7bd0d1e187e3)

2024-03-19 13:03 UTC, DmitrijEgorow commented
Я бы обрезал под квадрат
![Screenshot_20240319_155624](https://github.com/purpleratchet/PlaylistMaker/assets/36837067/7ecb1a0c-a40a-4952-911e-087b8b2e8742)

2024-03-19 13:03 UTC, DmitrijEgorow commented
https://github.com/purpleratchet/PlaylistMaker/assets/36837067/6175493c-51ad-48eb-9a22-4a247611de14

2024-03-19 13:04 UTC, DmitrijEgorow commented
```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 2481  
retrofit2.HttpException: HTTP 404  
at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)  
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)  
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)  
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)  
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)  
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)  
at java.lang.Thread.run(Thread.java:1012)  
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b060afd, Dispatchers.Main.immediate]
```



https://github.com/purpleratchet/PlaylistMaker/assets/36837067/3903c19e-e799-43d8-a131-a0270c5d9fe8

2024-03-19 13:04 UTC, DmitrijEgorow commented
```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 11599  
java.lang.IllegalStateException  
at android.media.MediaPlayer.getCurrentPosition(Native Method)  
at com.example.playlistmaker.player.data.PlayerRepositoryImpl.getCurrentPosition(PlayerRepositoryImpl.kt:24)  
at com.example.playlistmaker.player.domain.impl.PlayerInteractorImpl.getCurrentPosition(PlayerInteractorImpl.kt:36)  
at com.example.playlistmaker.player.ui.viewmodel.PlayerViewModel.getCurrentPosition(PlayerViewModel.kt:91)  
at com.example.playlistmaker.player.ui.viewmodel.PlayerViewModel.access$getCurrentPosition(PlayerViewModel.kt:21)  
at com.example.playlistmaker.player.ui.viewmodel.PlayerViewModel$updateTime$1.invokeSuspend(PlayerViewModel.kt:101)  
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)  
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)  
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)  
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)  
at kotlinx.coroutines.android.HandlerContext[scheduleResumeAfterDelay](tex://scheduleResumeAfterDelay)[inlined](tex://inlined)Runnable$1.run(Runnable.kt:19)  
at android.os.Handler.handleCallback(Handler.java:938)  
at android.os.Handler.dispatchMessage(Handler.java:99)  
at android.os.Looper.loopOnce(Looper.java:226)  
at android.os.Looper.loop(Looper.java:313)
```



https://github.com/purpleratchet/PlaylistMaker/assets/36837067/ba926cec-3d83-4362-83b5-e1ffee105e23

2024-03-25 20:02 UTC, DmitrijEgorow commented
Новый баг с кнопкой play/pause, которого раньше не было


https://github.com/purpleratchet/PlaylistMaker/assets/36837067/82a80121-2a07-4faf-9ace-efb944dee282

2024-03-25 20:04 UTC, DmitrijEgorow commented
> Стоит динамически растягивать/сжимать изображение плейсхолдера, это обеспечит адаптивность разметки
> 
> ![Screenshot_20240319_152549](https://private-user-images.githubusercontent.com/36837067/314062726-cffb43d8-4a56-43a8-8e72-7bd0d1e187e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTY3NzIsIm5iZiI6MTcxMTM5NjQ3MiwicGF0aCI6Ii8zNjgzNzA2Ny8zMTQwNjI3MjYtY2ZmYjQzZDgtNGE1Ni00M2E4LThlNzItN2JkMGQxZTE4N2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmY0OTI5ZTRkZDIwOGUxZTJhMmFiMTE2ZTllYTEzMzhlZDcxYzhhNjk1YmM5MmZjODU4ZGUzY2ZmOTY1NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDBfWBDMZM-KDa99P55fAERhNMPg218Xof8OcbK4AMI)

Остаётся актуальным

2024-05-27 09:47 UTC, merged